### ISSUE TITLE
Install on Nvidia GPU

### ISSUE THREAD

**Issue by YumengYan** [haddocking/powerfit#14]
Thanks for developing this useful tool. I have used it on CPUs and it works well. But when I tried to run it on GPUs, I meet some problems, maybe about the OpenCL on GPU? I actually don't know what cause the problem. When I tried to run the _test_gpyfft.py_, 
I get the error message, **ERROR: setUpClass (__main__.TestCLKernels)**, and Traceback message is **AttributeError: 'NoneType' object has no attribute 'context'**.  I installed "pocl                      1.2               h6bb024c_1002    conda-forge/label/gcc7". Could you help me fix that? Many thanks!

**Comment by latrocinia** [comment]
Hi Yemeng, could you provide information on which system you are working and which packages you installed? Were you able to install `pyopencl` and `gpyfft`?

**Comment by YumengYan** [comment]
Sorry about that. I have run it successfully on GPU. I should close this issue.

**Comment by amjjbonvin** [comment]
May-be post the solution to this thread first?

**Comment by YumengYan** [comment]
I am using a GPU cluster with a head node. First, I installed OpenCL, pyopencl and gpyfft on the head node with no GPU, and this was the reason that I failed to run powerfit on GPU nodes. When I used srun (SLURM command) to install the packages on the GPU nodes, and it worked.

**Comment by amjjbonvin** [comment]
Thanks!
